name: "Lint PR for Semantic Bump"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
jobs:
  LintPRForSemanticBump:
    runs-on: ubuntu-latest
    steps:
      # Please look up the latest version from
      # https://github.com/amannn/action-semantic-pull-request/releases
      - uses: amannn/action-semantic-pull-request@v4.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
